// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package raft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogEntry struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	CommandName          string   `protobuf:"bytes,3,opt,name=CommandName,proto3" json:"CommandName,omitempty"`
	Command              []byte   `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type AppendEntriesReq struct {
	Term                 int64       `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderName           string      `protobuf:"bytes,2,opt,name=LeaderName,proto3" json:"LeaderName,omitempty"`
	PrevLogIndex         int64       `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          int64       `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	LeaderCommit         int64       `protobuf:"varint,5,opt,name=LeaderCommit,proto3" json:"LeaderCommit,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,6,rep,name=Entries,proto3" json:"Entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesReq) Reset()         { *m = AppendEntriesReq{} }
func (m *AppendEntriesReq) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesReq) ProtoMessage()    {}
func (*AppendEntriesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *AppendEntriesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesReq.Unmarshal(m, b)
}
func (m *AppendEntriesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesReq.Marshal(b, m, deterministic)
}
func (m *AppendEntriesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesReq.Merge(m, src)
}
func (m *AppendEntriesReq) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesReq.Size(m)
}
func (m *AppendEntriesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesReq proto.InternalMessageInfo

func (m *AppendEntriesReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *AppendEntriesReq) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

func (m *AppendEntriesReq) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	ConflictTerm         int64    `protobuf:"varint,3,opt,name=ConflictTerm,proto3" json:"ConflictTerm,omitempty"`
	ConflictIndex        int64    `protobuf:"varint,4,opt,name=ConflictIndex,proto3" json:"ConflictIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResp) Reset()         { *m = AppendEntriesResp{} }
func (m *AppendEntriesResp) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResp) ProtoMessage()    {}
func (*AppendEntriesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *AppendEntriesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResp.Unmarshal(m, b)
}
func (m *AppendEntriesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResp.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResp.Merge(m, src)
}
func (m *AppendEntriesResp) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResp.Size(m)
}
func (m *AppendEntriesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResp proto.InternalMessageInfo

func (m *AppendEntriesResp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResp) GetConflictTerm() int64 {
	if m != nil {
		return m.ConflictTerm
	}
	return 0
}

func (m *AppendEntriesResp) GetConflictIndex() int64 {
	if m != nil {
		return m.ConflictIndex
	}
	return 0
}

type RequestVoteReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LastLogIndex         int64    `protobuf:"varint,2,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,3,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	CandidateName        string   `protobuf:"bytes,4,opt,name=CandidateName,proto3" json:"CandidateName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteReq) Reset()         { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()    {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *RequestVoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReq.Unmarshal(m, b)
}
func (m *RequestVoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReq.Marshal(b, m, deterministic)
}
func (m *RequestVoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReq.Merge(m, src)
}
func (m *RequestVoteReq) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReq.Size(m)
}
func (m *RequestVoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReq proto.InternalMessageInfo

func (m *RequestVoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *RequestVoteReq) GetCandidateName() string {
	if m != nil {
		return m.CandidateName
	}
	return ""
}

type RequestVoteResp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResp) Reset()         { *m = RequestVoteResp{} }
func (m *RequestVoteResp) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResp) ProtoMessage()    {}
func (*RequestVoteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *RequestVoteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResp.Unmarshal(m, b)
}
func (m *RequestVoteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResp.Marshal(b, m, deterministic)
}
func (m *RequestVoteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResp.Merge(m, src)
}
func (m *RequestVoteResp) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResp.Size(m)
}
func (m *RequestVoteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResp proto.InternalMessageInfo

func (m *RequestVoteResp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResp) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type InstallSnapshotReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderName           string   `protobuf:"bytes,2,opt,name=LeaderName,proto3" json:"LeaderName,omitempty"`
	LastIncludedIndex    int64    `protobuf:"varint,3,opt,name=LastIncludedIndex,proto3" json:"LastIncludedIndex,omitempty"`
	LastIncludedTerm     int64    `protobuf:"varint,4,opt,name=LastIncludedTerm,proto3" json:"LastIncludedTerm,omitempty"`
	Offset               int64    `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Done                 bool     `protobuf:"varint,7,opt,name=Done,proto3" json:"Done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotReq) Reset()         { *m = InstallSnapshotReq{} }
func (m *InstallSnapshotReq) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotReq) ProtoMessage()    {}
func (*InstallSnapshotReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *InstallSnapshotReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotReq.Unmarshal(m, b)
}
func (m *InstallSnapshotReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotReq.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotReq.Merge(m, src)
}
func (m *InstallSnapshotReq) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotReq.Size(m)
}
func (m *InstallSnapshotReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotReq.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotReq proto.InternalMessageInfo

func (m *InstallSnapshotReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotReq) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *InstallSnapshotReq) GetLastIncludedIndex() int64 {
	if m != nil {
		return m.LastIncludedIndex
	}
	return 0
}

func (m *InstallSnapshotReq) GetLastIncludedTerm() int64 {
	if m != nil {
		return m.LastIncludedTerm
	}
	return 0
}

func (m *InstallSnapshotReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *InstallSnapshotReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InstallSnapshotReq) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type InstallSnapshotResp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotResp) Reset()         { *m = InstallSnapshotResp{} }
func (m *InstallSnapshotResp) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotResp) ProtoMessage()    {}
func (*InstallSnapshotResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *InstallSnapshotResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotResp.Unmarshal(m, b)
}
func (m *InstallSnapshotResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotResp.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotResp.Merge(m, src)
}
func (m *InstallSnapshotResp) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotResp.Size(m)
}
func (m *InstallSnapshotResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotResp.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotResp proto.InternalMessageInfo

func (m *InstallSnapshotResp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterType((*AppendEntriesReq)(nil), "AppendEntriesReq")
	proto.RegisterType((*AppendEntriesResp)(nil), "AppendEntriesResp")
	proto.RegisterType((*RequestVoteReq)(nil), "RequestVoteReq")
	proto.RegisterType((*RequestVoteResp)(nil), "RequestVoteResp")
	proto.RegisterType((*InstallSnapshotReq)(nil), "InstallSnapshotReq")
	proto.RegisterType((*InstallSnapshotResp)(nil), "InstallSnapshotResp")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0xe5, 0xdd, 0x34, 0xdb, 0xce, 0x96, 0xd2, 0x1a, 0x84, 0x7c, 0x42, 0x91, 0xe1, 0xb0,
	0x20, 0xd4, 0x03, 0x3c, 0x01, 0x14, 0x54, 0xad, 0xb4, 0x02, 0x94, 0x22, 0x0e, 0xdc, 0x4c, 0x3c,
	0x5b, 0x56, 0x4a, 0xec, 0x34, 0xf6, 0x22, 0x78, 0x06, 0x2e, 0xbc, 0x1c, 0x2f, 0xc0, 0x93, 0x20,
	0x4f, 0x9c, 0xca, 0x61, 0xdb, 0x4b, 0x6f, 0xfe, 0x3f, 0x27, 0x33, 0xff, 0x3f, 0x99, 0xc0, 0x51,
	0xdb, 0x59, 0x6f, 0x2b, 0x5b, 0x9f, 0xd2, 0x41, 0xb6, 0xb0, 0xbf, 0xb2, 0x97, 0xef, 0x8c, 0xef,
	0x7e, 0xf2, 0x87, 0xb0, 0xb7, 0x34, 0x1a, 0x7f, 0x08, 0x56, 0xb0, 0xc5, 0xb4, 0xec, 0x05, 0xe7,
	0x90, 0x7d, 0xc2, 0xae, 0x11, 0x13, 0x82, 0x74, 0xe6, 0x05, 0xcc, 0xcf, 0x6c, 0xd3, 0x28, 0xa3,
	0xdf, 0xab, 0x06, 0xc5, 0xb4, 0x60, 0x8b, 0x83, 0x32, 0x45, 0x5c, 0xc0, 0x2c, 0x4a, 0x91, 0x15,
	0x6c, 0x71, 0x58, 0x0e, 0x52, 0xfe, 0x61, 0x70, 0xfc, 0xba, 0x6d, 0xd1, 0xe8, 0xd0, 0x75, 0x83,
	0xae, 0xc4, 0xab, 0xeb, 0x26, 0x2c, 0x69, 0xf2, 0x18, 0x60, 0x85, 0x4a, 0x63, 0x47, 0x3d, 0x26,
	0xd4, 0x23, 0x21, 0x5c, 0xc2, 0xe1, 0xc7, 0x0e, 0xbf, 0xaf, 0xec, 0x65, 0xef, 0x7a, 0x4a, 0xef,
	0x8e, 0x58, 0x30, 0x1a, 0x35, 0x95, 0xcf, 0xe8, 0x91, 0x14, 0x85, 0x2a, 0x7d, 0xcd, 0xe0, 0x6f,
	0xe3, 0xc5, 0x5e, 0x5f, 0x25, 0x65, 0xfc, 0x09, 0xcc, 0xa2, 0x57, 0x91, 0x17, 0xd3, 0xc5, 0xfc,
	0xe5, 0xc1, 0xe9, 0x30, 0xb4, 0x72, 0xb8, 0x91, 0xbf, 0x18, 0x9c, 0xfc, 0x97, 0xcb, 0xb5, 0x37,
	0x06, 0x13, 0x30, 0xbb, 0xd8, 0x56, 0x15, 0x3a, 0x47, 0xa9, 0xf6, 0xcb, 0x41, 0x06, 0x33, 0x67,
	0xd6, 0xac, 0xeb, 0x4d, 0xe5, 0xe9, 0xad, 0x18, 0x29, 0x65, 0xfc, 0x29, 0xdc, 0x1b, 0x74, 0x9f,
	0xbb, 0x0f, 0x35, 0x86, 0xf2, 0x37, 0x83, 0xa3, 0x12, 0xaf, 0xb6, 0xe8, 0xfc, 0x67, 0xeb, 0xf1,
	0xb6, 0x19, 0x87, 0xf4, 0xca, 0xf9, 0xeb, 0x19, 0x4e, 0x62, 0xfa, 0x84, 0x85, 0x19, 0x46, 0x9d,
	0x78, 0x4a, 0x11, 0x59, 0x52, 0x46, 0x6f, 0xb4, 0xf2, 0x48, 0x1f, 0x2b, 0xa3, 0x8f, 0x35, 0x86,
	0xf2, 0x1c, 0xee, 0x8f, 0x1c, 0xdd, 0x32, 0x9d, 0x02, 0xe6, 0xe1, 0xfe, 0xbc, 0x53, 0xc6, 0xa3,
	0x8e, 0x13, 0x4a, 0x91, 0xfc, 0xcb, 0x80, 0x2f, 0x8d, 0xf3, 0xaa, 0xae, 0x2f, 0x8c, 0x6a, 0xdd,
	0x37, 0xeb, 0xef, 0xba, 0x43, 0x2f, 0xe0, 0x24, 0x04, 0x59, 0x9a, 0xaa, 0xde, 0x6a, 0xd4, 0xe9,
	0x22, 0xed, 0x5e, 0xf0, 0xe7, 0x70, 0x9c, 0xc2, 0x64, 0xa5, 0x76, 0x38, 0x7f, 0x04, 0xf9, 0x87,
	0xf5, 0xda, 0xe1, 0xb0, 0x51, 0x51, 0x05, 0x97, 0x6f, 0x95, 0x57, 0x22, 0xa7, 0xbf, 0x82, 0xce,
	0xc4, 0xac, 0x41, 0x31, 0xa3, 0xac, 0x74, 0x96, 0xcf, 0xe0, 0xc1, 0x4e, 0xc6, 0x9b, 0x27, 0xf6,
	0x26, 0xff, 0x92, 0x75, 0x6a, 0xed, 0xbf, 0xe6, 0xf4, 0x4b, 0xbf, 0xfa, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0xe8, 0xdc, 0xd0, 0xe4, 0x03, 0x00, 0x00,
}
